# Bottom temperature - Seasonal Gridded

**Description**: Seasonal mean bottom temperatures on the Northeast Continental Shelf between 1959 and 2023 in a 1/12° grid.

**Indicator family**: 

- [X] Oceanographic
- [ ] Habitat
- [ ] Lower trophic levels
- [ ] Megafauna
- [ ] Social
- [ ] Economic

**Contributor(s)**: Joseph Caracappa, Hubert du Pontavice, Vincent Saba, Zhuomin Chen

**Affiliations**: NEFSC

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
library(ecodata)
```
## Indroduction to Indicator
The bottom temperature product is in a horizontal 1/12 degree grid between 1959 and 2022 and is made of daily bottom temperature estimates from:

Bias-corrected ROMS-NWA between 1959 and 1992 which was regridded in the same 1/12degree grid as GLORYS using bilinear interpolation; Years 1993 through summer 2023 are from CMEMS GLORYS12V1 global reanalysis bottom temperature, and fall 2023 is from CMEMS PSY forecasting product.

## Key Results and Visualizations
Maps of seasonal mean bottom temperature across NE shelf.

