# Ocean Acidification and Shellfish

**Description**: Ocean acidification measures in the Mid-Atlantic and lab affects of OA on bivalves

**Found in**: 

**Indicator category**: Published Methods 

**Contributor(s)**: Pousse E, Poach ME, Redman DH, Sennefelder G, White LE, Lindsay JM, Munroe D, Hart D, Hennen D, Dixon MS, Li Y, Gary Wikfors, Shannon Meseck and Elizabeth K. Wright‐Fairbanks Travis N. Miles Wei‐Jun Cai Baoshan Chen Grace K. Saba
  
**Data steward**: Shannon Meseck and Grace Saba
  
**Point of contact**: Shannon Meseck and Grace Saba
  
**Public availability statement**: Published Methods

## Impact Summary

pH in the Mid-Atlantic was measured using glider (@wright2020). These results show summertime pH around 7.8 in the depth regions in which Atlantic Surfclam (*Spisula solidissima*) and Atlantic Sea Scallop (*Placopecten magellanicus*) are found. 

Atlantic surfclam exposure to ocean acidification research in the laboratory for larvae and juvenile found that increased acidification resulted in changes in growth rates.  Juvenile surfclams have a complex response to OA by adopting two different metabolic strategies as a function of CO2 concentrations (Pousse et al. 2020).  It appears that surfclams have a metabolic depression in a pH range of 7.46-7.28 making them more sensitive than estuarine species to OA.  There is a decrease in clearance rates (movement of water) , the amount of organic matter ingested decreases, and the assimilation rate  with increased OA.  Once the food is ingested there is no change in how they process the food (assimilation efficiency), but their ability to select and clear food does change under OA. In addition to changes in how they filter, there was a difference in shell weight.  Increased OA resulted in lighter shells.  Larval appear to also be sensitive to OA (Meseck et al., in press).  Results of larvae suggest that levels above 800 ppm results in decreased growth.  For both larvae and juveniles there was no difference in survival.  It is unclear at this time what the effects on reproduction and recruitment would be.   Currently dynamic energy budget models are being constructed using Pousse et al. (2020) data to predict how surfclams will respond to OA by the year 2100.  It is noted that a project by PI Poach and Hennan was recently funded to do field analysis of Atlantic surfclam (both subspecies) trying to link OA and growth in the field.   

### Plotting

Code for plotting can be found [here](https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-mab-oa.R).

<!-- ```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-mab-oa-glider.R"), eval=TRUE, echo = FALSE} -->

<!-- ``` -->

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-mab-oa.R"), eval=TRUE, echo = FALSE}

```


### Methods
See @wright2020 for glider study and @pousse2020 for lab study. 


