# Survey Impacts from Offshore Energy Development {#osw_survey_impact}

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
library(ecodata)
library(downloadthis)
```

*Last updated July 23, 2026*

**Description**: Offshore energy development is expected to have several impacts on federal and state surveys.

**Contributor(s)**: Douglas Christel

**Affiliations**: GARFO

**Indicator Family**: 

- [X] Social


**Indicator Category**:

- [X] Syntheses of published information


**Synthesis Theme**:

- [X] Multiple System Drivers


## Introduction to Indicator
Proceed as though this were a short summary of a typical introduction section in a paper.

## Key Results and Visualizations
Proceed as though this were a short summary of a typical results section in a paper.

## Implications
Proposed energy development areas interact with the region’s federal scientific surveys @friedland_spatial_2023. Scientific surveys are impacted by offshore energy in four ways:
 1)  Exclusion of NOAA Fisheries’ sampling platforms from the energy development area due to operational and safety limitations;
 2)  Impacts on the random-stratified statistical design that is the basis for scientific assessments, advice, and analyses; 
3) Alteration of benthic and pelagic habitats, and airspace in and around the energy development, requiring new designs and methods to sample new habitats; and, 
4) Reduced sampling productivity through navigation impacts of energy infrastructure on aerial and vessel survey operations. 

Increased vessel transit between stations may decrease data collections that are already limited by annual days-at-sea day allocations. The total survey area overlap ranges from 1-70% for all Greater Atlantic federal surveys. The Gulf of Maine Cooperative Research Bottom Longline Survey (41%) and the Shrimp Survey (70%) have the largest percent overlap with the draft Gulf of Maine Energy Areas. The remaining surveys range from 1-16% overlap.  Individual survey strata have significant interaction with energy areas, including the sea scallop survey (up to 96% of individual strata) and the bottom trawl survey (BTS, up to 60% strata overlap). Additionally, up to 50% of the southern New England North Atlantic right whale survey’s area overlaps with proposed project areas and a region-wide survey mitigation program is underway @northeast_fisheries_science_center_us_fall_2022

## Indicator statistics 
Spatial scale: full shelf

Temporal scale: Decadal

**Variable definitions**

No Data

## Get the data

**Point of contact**: douglas.christel@noaa.gov

### Public Availability

Source data are publicly available.

