# Timing shifts: Risks to Seasonal Management {#timing_shifts}

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
library(ecodata)
library(downloadthis)
```

*Last updated July 23, 2026*

**Description**: Shifts in the timing of life-cycle events are a risk to meeting seasonal and temporal management objectives.

**Contributor(s)**: Kimberly Hyde, Sarah Gaichas, Joe Carracappa

**Affiliations**: NEFSC

**Indicator Family**: 

- [X] Oceanographic
- [X] Habitat
- [X] Lower trophic levels
- [X] Megafauna


**Indicator Category**:

- [X] Syntheses of published information


**Synthesis Theme**:

- [X] Multiple System Drivers


## Introduction to Indicator
Changes in phenology, the seasonal timing of recurring life-cycle events, are a primary indicator of species responses to climate change @staudinger_its_2019. Observed phenological changes on the Northeast Shelf include shifts in [spawning](https://noaa-edab.github.io/catalog/spawn_timing.html), migration @crear_climate-influenced_2023, prey availability, and seasonal phytoplankton bloom timing. Changes in the timing of physical drivers such as the onset of stratification and fall turnover timing directly and indirectly affect life-cycle events. The phenological responses are often species-specific and vary depending on the primary environmental driver @staudinger_its_2019.

## Key Results and Visualizations
Migration timing of some tuna and large whale species has changed. For example, tuna were caught in recreational fisheries 50 days earlier in the year in 2019 compared to 2002. 

@crear_climate-influenced_2023 analyzed the timing of when the first 25% of intercepts occurred by year and state for recreationally important HMS between 2019 and 2022. Bigeye tuna were caught in recreational fisheries 50 days earlier (Fig 1a); small and large bluefin intercepted in Massachusetts were caught 38 and 80 days earlier (Fig 1b), respectively; blue sharks in Connecticut were captured 66 days earlier (Fig 1e); and blue marlin in New York were captured 27 days earlier (Fig 1g).

![Figure 1. Raw and predicted values for day of the year when 25% of intercepts occurred for each year for highly migratory species (HMS) where year was significant: Bigeye tuna (a), large bluefin tuna (b), small bluefin tuna (c), skipjack tuna (d), blue shark (e), shortfin mako (f), and blue marlin (g). Dashed lines indicate raw day-of-year values each year, whereas solid lines indicate the predicted day-of-year values. Plots where only black lines exist indicates there was no significant interaction between year and state intercept (a,d). For all other plots, colors represent the raw and predicted day-of-year values for each state for that species. Abbreviated states are CT, Connecticut; DE, Delaware; MA, Massachusetts; MD, Maryland; ME, Maine; NH, New Hampshire; NJ, New Jersey; NY, New York; RI, Rhode Island; VA, Virginia. Source: reprinted from Crear et al. 2023 (Fig 5)](https://github.com/NOAA-EDAB/ecodata/raw/dev/data-raw/workshop/images/multispecies_lower_timing-JenCudney_2025.png){width=100%}


In Cape Cod Bay, peak spring habitat use by right and humpback whales has shifted 18-19 days later over time. [@pendleton_decadal-scale_2022] 

Prolonged fall temperatures have been linked to the increased number of cold-stunned Kemp’s ridley sea turtles found in Cape Cod Bay [@griffin_warming_2019]

## Implications
Changes in phenology are key indicators of the effects of climate change on ecosystems and well documented in terrestrial ecosystems @cohen_global_2018. Trends in phenology are often not homogenous due to high variability in climate drivers and phenological responses @okeefe_forming_2013. Phenological changes are less well documented in marine ecosystems, but there are clear, documented shifts in the timing of seasonal marine abiotic factors including earlier [transitions](https://noaa-edab.github.io/catalog/trans_dates.html) from winter to spring temperatures in the Northeast Continental Shelf @friedland_changes_2020; @thomas_seasonal_2017. Lower trophic levels, phytoplankton and zooplankton, are able to quickly adapt to abiotic changes, which can lead to a mismatch with consumers and alter the food web structure. Differential shifts in phenology can drive population declines through increased predation or competition and/or declines in reproductive success @weiskopf_climate_2020

From a management perspective, changes in species-specific phenology can alter fishery interactions and bycatch, as well as reduce the effectiveness of time/area closures to protect sensitive seasonal processes such as spawning. Highly migratory species are susceptible to incidental catch in a large number of fisheries using a variety of fishing gears @okeefe_forming_2013, and changes in migration timing may increase these unintended interactions if seasonal measures do not adjust to these changes.

## Indicator statistics 
Spatial scale: NES

Temporal scale: Seasonal

**Variable definitions**

NA

## Get the data

**Point of contact**: nefsc.soe.leads@noaa.gov

### Public Availability

Source data are publicly available.

